### PR TITLE
Carthage: Add macOS, tvOS and watchOS to shared Frameworks

### PR DESCRIPTION
**Pull request by mRs-**
Currently only iOS is supported for Carthage

### CODE REVIEW

**Review by icanzilb — APPROVED** [review]
Thanks!

**Comment by icanzilb** [comment]
@mRs- I think I'll have to revert that change - it makes TimelaneCombine and RxTimelane fail to compile. Do you happen to know what issue might be?

**Comment by mRs-** [comment]
Mmhhh that’s Strange. It’s working fine on my machine. Will look into it as soon as possible with a clean checkout

**Comment by icanzilb** [comment]
That's the thing - this change isn't in a release yet. If you build TimelaneCombine with a dependency on TimelaneCore/master you will see the crash

**Comment by icanzilb** [comment]
I build backwards commit by commit and the build starts crashing on this commit. (Got to add CI to this repo some time soon to catch stuff like this)

**Comment by icanzilb** [comment]
Sorry, reversed that commit and updated all repos. If you still need it let's work to make a synchronized release making sure dependent repos don't break

**Pull request merged**
