### PR TITLE
Add PodSpec file to enable Cocoapods Support

### PR DESCRIPTION
**Pull request by KarimEbrahemAbdelaziz**
## Why this PR ?
- To be able to use TimelaneCombine in Cocapods we need it's dependencies as Pods too.
## Who will upload this Pod ?
- I would prefer you Marin to upload this pod.

### CODE REVIEW

**Review by icanzilb — APPROVED** [review]
Thanks :) Let's get this merged

**Comment by KarimEbrahemAbdelaziz** [comment]
@icanzilb Great, thank you Marin. 
Please let me know once you uploaded it successfully as a Pod.

**Comment by icanzilb** [comment]
--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  TimelaneCore (1.0.2) successfully published
 📅  March 9th, 09:15
 🌎  https://cocoapods.org/pods/TimelaneCore
 👍  Tell your friends!
--------------------------------------------------------------------------------

**Comment by KarimEbrahemAbdelaziz** [comment]
Great 🔥
I will make another PR now on TimelaneCombine to support cocoapods too 💪🏻

**Pull request merged**
