### PR TITLE
Fix issues when linking in app extension

### LINKED ISSUE #32: Cannot use in app extension
Hey Marin,

I want to use Timelane in a shared library which is both used in an app and in an app extension.
But I get this issue:

```
ld: warning: linking against a dylib which is not safe for use in application extensions: /Users/jandamm/Library/Developer/Xcode/DerivedData/MyProject-hblpzjxpsslhyaazlcklhyaxxonk/Build/Products/Release-iphoneos/PackageFrameworks/TimelaneCombine_-469EAF36A8B98E05_PackageProduct.framework/TimelaneCombine_-469EAF36A8B98E05_PackageProduct
```

The library uses `Allow app extension API only`.

I guess this is just one missing flag but I don't know how to set this with SPM 😅

### PR DESCRIPTION
**Pull request by jandamm**
Closes #32

### CODE REVIEW

**Comment by jandamm** [comment]
I've tested it with the setting described in the linked issue.
Events showed up when the library is used inside the app.
I didn't test the extension.

**Review by icanzilb — CHANGES_REQUESTED** [review]
This looks good to me, I had no idea this is a linker flag. Have you tried actually using the code from an app extension — I thought this was your original use case?

**Comment by jandamm** [comment]
My primary goal was to be able to use Timelane in a shared library which is imported into an app extension - which produced a build error before.

Just debugging in the app would have been fine for me.
But I just confirmed the extension is also sending events to Timelane 👍

**Comment by icanzilb** [comment]
Amazing, thank you @jandamm !

**Review by icanzilb — APPROVED** [review]

**Comment by icanzilb** [comment]
Released in https://github.com/icanzilb/TimelaneCore/releases/tag/2.0.1

**Pull request merged**
